
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions name="EmpresaEmpleoServicePRD"
                  targetNamespace="http://mdwcorp.falabella.com/OSB/wsdl/BCO/CO/empresa/empleo/obtener-v1.1"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://mdwcorp.falabella.com/OSB/wsdl/BCO/CO/empresa/empleo/obtener-v1.1"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:xsd1="http://mdwcorp.falabella.com/OSB/schema/BCO/CO/empresa/empleo/obtener/Req-v2015.06"
                  xmlns:xsd2="http://mdwcorp.falabella.com/OSB/schema/BCO/CO/empresa/empleo/obtener/Resp-v2015.06"
                  xmlns:xsd4="http://schemas.xmlsoap.org/soap/envelope/">
    <wsdl:types>
	    <xsd:schema
			targetNamespace="http://mdwcorp.falabella.com/WLS/wsdl/BCO/CO/empresa/empleo/obtener-v1.1">
			<xsd:element name="EmpresaEmpleoOpFault" type="xsd:string"></xsd:element>
		</xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://mdwcorp.falabella.com/OSB/schema/BCO/CO/empresa/empleo/obtener/Req-v2015.06"
                        schemaLocation="../Schemas/WLS_Empresa_Empleo_ObtenerReq.xsd">
            </xsd:import>
            <xsd:import namespace="http://mdwcorp.falabella.com/OSB/schema/BCO/CO/empresa/empleo/obtener/Resp-v2015.06"
                        schemaLocation="../Schemas/WLS_Empresa_Empleo_ObtenerResp.xsd">
            </xsd:import>
            <xsd:import namespace="http://schemas.xmlsoap.org/soap/envelope/"
				schemaLocation="../../../BCO_CO_UT_Esquemas_Comunes/Specifications/XSD/Common/SoapFault.xsd">
			</xsd:import>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="EmpresaEmpleoMsgReq">
        <wsdl:part name="EmpresaEmpleoReqParam" element="xsd1:ObtenerEmpleoEmpresaReq"/>
    </wsdl:message>
    <wsdl:message name="EmpresaEmpleoMsgResp">
        <wsdl:part name="EmpresaEmpleoRespParam" element="xsd2:ObtenerEmpleoEmpresaResp"/>
    </wsdl:message>
    <wsdl:message name="EmpresaEmpleoOpFault">
        <wsdl:part name="EmpresaEmpleoFaultParam" element="xsd4:Fault"/>
    </wsdl:message>


    <wsdl:portType name="EmpresaEmpleoPt">
        <wsdl:operation name="EmpresaEmpleoOp">
            <wsdl:input message="tns:EmpresaEmpleoMsgReq"/>
            <wsdl:output message="tns:EmpresaEmpleoMsgResp"/>
            <wsdl:fault name="fault" message="tns:EmpresaEmpleoOpFault"></wsdl:fault>
        </wsdl:operation>
    </wsdl:portType>


    <wsdl:binding name="EmpresaEmpleoBinding" type="tns:EmpresaEmpleoPt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="EmpresaEmpleoOp">
            <soap:operation soapAction="http://mdwcorp.falabella.com/OSB/wsdl/BCO/CO/empresa/empleo/obtener-v1.1/Op"/>
            <wsdl:input>
                <soap:body use="literal" parts="EmpresaEmpleoReqParam"/>
                <soap:header use="literal" part="EmpresaEmpleoHeaderParam" message="tns:EmpresaEmpleoMsgReq"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="EmpresaEmpleoRespParam"/>
            </wsdl:output>
            <wsdl:fault name="fault">
                <soap:fault name="fault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>


    <wsdl:service name="EmpresaEmpleoServicePRD">
        <wsdl:port binding="tns:EmpresaEmpleoBinding" name="EmpresaEmpleoPortPRD">
            <soap:address location="BCO/CO/empresa/V1_0/empleoObtener"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>