
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions name="TarjetaCreditoMovimientoDetalleObtenerServicePRD"
                  targetNamespace="http://mdwcorp.falabella.com/OSB/wsdl/BCO/CO/Credito/tarjetacredito/movimientodetalle/obtener-v1.0"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://mdwcorp.falabella.com/OSB/wsdl/BCO/CO/Credito/tarjetacredito/movimientodetalle/obtener-v1.0"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:xsd1="http://mdwcorp.falabella.com/WLS/schema/BCO/CO/Credito/tarjetacredito/movimientodetalle/obtener/Req-v2015.06"
                  xmlns:xsd2="http://mdwcorp.falabella.com/WLS/schema/BCO/CO/Credito/tarjetacredito/movimientodetalle/obtener/Resp-v2015.06"
                  xmlns:xsd4="http://schemas.xmlsoap.org/soap/envelope/">
    <wsdl:types>
	    <xsd:schema
			targetNamespace="http://mdwcorp.falabella.com/WLS/wsdl/BCO/CO/Credito/tarjetacredito/movimientodetalle/obtener-v1.0">
			<xsd:element name="TarjetaCreditoMovimientoDetalleObtenerOpFault" type="xsd:string"></xsd:element>
		</xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://mdwcorp.falabella.com/WLS/schema/BCO/CO/Credito/tarjetacredito/movimientodetalle/obtener/Req-v2015.06"
                        schemaLocation="../Schemas/WLS_TarjetaCredito_MovimientoDetalle_ObtenerReq.xsd">
            </xsd:import>
            <xsd:import namespace="http://mdwcorp.falabella.com/WLS/schema/BCO/CO/Credito/tarjetacredito/movimientodetalle/obtener/Resp-v2015.06"
                        schemaLocation="../Schemas/WLS_TarjetaCredito_MovimientoDetalle_ObtenerResp.xsd">
            </xsd:import>
            <xsd:import namespace="http://schemas.xmlsoap.org/soap/envelope/"
				schemaLocation="../../../BCO_CO_UT_Esquemas_Comunes/Specifications/XSD/Common/SoapFault.xsd">
			</xsd:import>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="TarjetaCreditoMovimientoDetalleObtenerMsgReq">
        <wsdl:part name="TarjetaCreditoMovimientoDetalleObtenerReqParam" element="xsd1:TarjetaCreditoMovimientoDetalleObtenerProdReq"/>
    </wsdl:message>
    <wsdl:message name="TarjetaCreditoMovimientoDetalleObtenerMsgResp">
        <wsdl:part name="TarjetaCreditoMovimientoDetalleObtenerRespParam" element="xsd2:TarjetaCreditoMovimientoDetalleObtenerProdResp"/>
    </wsdl:message>
    <wsdl:message name="TarjetaCreditoMovimientoDetalleObtenerOpFault">
        <wsdl:part name="TarjetaCreditoMovimientoDetalleObtenerFaultParam" element="xsd4:Fault"/>
    </wsdl:message>


    <wsdl:portType name="TarjetaCreditoMovimientoDetalleObtenerPt">
        <wsdl:operation name="TarjetaCreditoMovimientoDetalleObtenerOp">
            <wsdl:input message="tns:TarjetaCreditoMovimientoDetalleObtenerMsgReq"/>
            <wsdl:output message="tns:TarjetaCreditoMovimientoDetalleObtenerMsgResp"/>
            <wsdl:fault name="fault" message="tns:TarjetaCreditoMovimientoDetalleObtenerOpFault"></wsdl:fault>
        </wsdl:operation>
    </wsdl:portType>


    <wsdl:binding name="TarjetaCreditoMovimientoDetalleObtenerBinding" type="tns:TarjetaCreditoMovimientoDetalleObtenerPt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="TarjetaCreditoMovimientoDetalleObtenerOp">
            <soap:operation soapAction="http://mdwcorp.falabella.com/OSB/wsdl/BCO/CO/Credito/tarjetacredito/movimientodetalle/obtener-v1.0/Op"/>
            <wsdl:input>
                <soap:body use="literal" parts="TarjetaCreditoMovimientoDetalleObtenerReqParam"/>
                <soap:header use="literal" part="TarjetaCreditoMovimientoDetalleObtenerHeaderParam" message="tns:TarjetaCreditoMovimientoDetalleObtenerMsgReq"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="TarjetaCreditoMovimientoDetalleObtenerRespParam"/>
            </wsdl:output>
            <wsdl:fault name="fault">
                <soap:fault name="fault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>


    <wsdl:service name="TarjetaCreditoMovimientoDetalleObtenerServicePRD">
        <wsdl:port binding="tns:TarjetaCreditoMovimientoDetalleObtenerBinding" name="TarjetaCreditoMovimientoDetalleObtenerPortPRD">
            <soap:address location="CO/tarjetacredito/v1_0/movimientodetalleObtener"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>